config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
    resources :farmer_products, only: [:new, :show, :create, :edit, :destroy]
    get "profile", to: "users#profile"

    resources :buyer_preferences, only: [:new, :create, :edit, :update]
    get "profile", to: "users#profile"

    get "dashboards", to: "dashboards#show"

    resources :farmer_transactions, only: [:new, :create, :index, :show] do
      resources :transaction_products, only: [:create]
    end

    get '/confirm/:id', to: 'farmer_transactions#confirm', as: :farmer_transaction_confirmation

    get 'request_for_buyer/:id', to: "farmer_transactions#request_for_buyer", as: :request_for_buyer
    post 'reject_transaction/:id', to: "farmer_transactions#reject_transaction", as: :reject_transaction
    post 'accept_transaction/:id', to: "farmer_transactions#accept_transaction", as: :accept_transaction
    get '/my_products', to: "farmer_products#my_products"
end

app/models/farmer_product.rb
class FarmerProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/farmer_product_controller.rb
class FarmerProductsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @farmer_product = FarmerProduct.new
  end

  def create
    @products = Product.all
    @farmer_product = FarmerProduct.new(farmer_product_params)
    @farmer_product.user = current_user
    if @farmer_product.save
      #change redirect to index
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def farmer_product_params
    params.require(:farmer_product).permit(:product_id)
  end
end

app/controllers/farmer_products_controller.rb
class FarmerProductsController < ApplicationController

  def new
    @farmer_product = FarmerProduct.new
  end

  def create
    @farmer_product = FarmerProduct.new(farmer_product_params)
    @farmer_product.user = current_user
    if @farmer_product.save
      #change redirect to index
      redirect_to my_products_path
    else
      render :new
    end
  end

  def edit
    @farmer_product = FarmerProduct.find(params[:id])
  end

  def update
  end

  def my_products
    @farmer_products = current_user.farmer_products
    @unavailable_products = []

    @farmer_products.each do |fp|
      @unavailable_products << fp.product
    end
    @products_available = Product.all - @unavailable_products
  end

  def destroy
    @farmer_product = FarmerProduct.find(params[:id])
    @farmer_product.destroy
    redirect_to my_products_path
  end

  private

  def farmer_product_params
    params.require(:farmer_product).permit(:product_id)
  end
end

app/views/farmer_products/_edit.html.erb
<%= simple_form_for fp do |f| %>
  <%= f.association :product, label: false %>
  <%= f.submit "Edit this product", class:'btn btn-transaction-small' %>
<% end %>

app/views/farmer_products/_new.html.erb
<%= simple_form_for fp, remote: true do |f| %>
  <div class="d-flex align-items-center mb-3 justify-content-between">
    <%= f.association :product, collection: @products_available, label: false %>
    <%= f.submit "Add product", class:'btn btn-transaction-small' %>
  </div>
<% end %>

app/views/farmer_products/my_products.html.erb
<div class="container">
  <div>
    <p class="text-center mt-2">
      <%= current_user.first_name %>, list your products
    </p>
  </div>
  <% @farmer_products.each do |fp| %>
    <div class="d-flex align-items-center mb-3 justify-content-between">
      <div class="d-flex align-items-center">
        <div class='mr-2'><%= image_tag fp.product.img_url, width: "30" %> </div>
        <p class="greeting mb-0"><%= fp.product.name.capitalize %> </p>
      </div>
      <!-- <i class="fas fa-trash-alt"></i> -->
      <%= link_to "", farmer_product_path(fp), remote: true, method: :delete, class:'fas fa-trash-alt btn-delete' %>
    </div>
  <% end %>
  <p>Add a new product</p>

    <%= render 'farmer_products/new', fp: FarmerProduct.new %>

</div>

app/views/farmer_products/new.html.erb
<h1>Add the products which you are growing here</h1>

 <div class="container">
  <%= simple_form_for @farmer_product do |f| %>
    <%= f.association :product %>
    <%= f.submit %>
  <% end %>
</div>

42
<!-- 1. this should not be a dropdown, but a form with multiple choice (checkbox)
displaying pictures for each product (product cards)
2.  instead of the create farmer product button, change it to
a button redirecting to the dashboard, when farmer is ready with
his selection of products.-->

app/views/farmer_products/show.html.erb
<h1>show one farmer product</h1>


<%= @farmer_product.product_id.name %>