config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
    resources :farmer_products, only: [:new, :show, :create, :edit, :destroy]
    get "profile", to: "users#profile"

    resources :buyer_preferences, only: [:new, :create, :edit, :update]
    get "profile", to: "users#profile"

    get "dashboards", to: "dashboards#show"

    resources :farmer_transactions, only: [:new, :create, :index, :show] do
      resources :transaction_products, only: [:create]
    end

    get '/confirm/:id', to: 'farmer_transactions#confirm', as: :farmer_transaction_confirmation

    get 'request_for_buyer/:id', to: "farmer_transactions#request_for_buyer", as: :request_for_buyer
    post 'reject_transaction/:id', to: "farmer_transactions#reject_transaction", as: :reject_transaction
    post 'accept_transaction/:id', to: "farmer_transactions#accept_transaction", as: :accept_transaction
    get '/my_products', to: "farmer_products#my_products"
end

app/views/shared/_card-buyer.html.erb
<div class="card-buyer mt-2 mx-1 pb-2">
  <div class="d-flex justify-content-between">
    <div class="avatar-container text-center mt-4 ml-4 mr-3">
      <%= image_tag user.img_url, alt: "User Avatar", class: "avatar-small" %>
      <p class="buyers-name mt-1 text-center"> <%= user.first_name %> <%= user.last_name %> </p>
    </div>
    <div class="mr-2">
      <div class="mt-4">
        <div class="row">
          <% user.buyer_preferences.each do |p| %>
            <div class="col-3 text-center d-flex flex-column justify-content-center">
              <div class="buyers-product ml-2 mr-2">
                <div>
                  <%= image_tag p.product.img_url, class: @product_array.include?(p.product.id) ? "avatar-product-match" : "avatar-product" %>
                </div>
                <div class='text-center'>
                 <p><%= p.price %>$</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user.transactions_as_farmer.where(buyer_id: user.id).any? %>

      <div class="row px-3">
        <div class="col text-right d-flex justify-content-end px-3">
          <p class="mb-0 mr-2">Status</p>
          <% if  current_user.transactions_as_farmer.where(buyer_id: user.id).first.status == "Accepted" %>
            <i class="fas fa-check-circle mt-1 accepted"></i>
          <% elsif current_user.transactions_as_farmer.where(buyer_id: user.id).first.status == "Declined" %>
            <i class="far fa-times-circle mt-1 declined"></i>
          <% elsif current_user.transactions_as_farmer.where(buyer_id: user.id).first.status == "Confirmed" %>
            <i class="fas fa-hourglass mt-1 pending"></i>
          <% end %>
        </div>
      </div>
  <% else %>

    <div class="row text-center">
      <div class="col">
        <%= link_to 'Sell!', new_farmer_transaction_path(user: user), class: "btn btn-main-small"%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_card-produce-farmer-transaction.erb
<div class="small-card-produce ml-1 mr-1">
  <div class="card-produce-img">
    <%= image_tag product.img_url, width: 50 %>
  </div>
  <div class="card-produce-info">
    <p class="greeting"> <%= product.name.capitalize %> </p>
    <p class="ml-2"> <%= price %>$</p>
  </div>
</div>

app/views/shared/_card-produce-quantity.html.erb
<div class="small-card-produce">
  <div class="card-produce-img">
    <%= image_tag product.img_url, width: 50 %>
  </div>
  <div class="card-produce-info">
    <p> <%= product.name.capitalize %> </p>
    <p class="ml-2"> <%= quantity %>kg </p>
  </div>
</div>

app/views/shared/_card-produce.html.erb
<!--
Keep this line and keep it to make product cards dynamic -->
<%#= render "shared/card-produce", product: @product %>


<div class="card-produce">
  <div class="card-produce-info greeting">
      <p> <%= product.name.capitalize %> </p>
      <!-- <p> 5 Buyers </p> -->
    </div>
  <div class="card-produce-img">
    <%= image_tag product.img_url, class: "avatar-product" %>
  </div>
<div class="card-produce-price">
 <!-- <strong><p> Average price: </p></strong> -->
 <p> <%= product.average_price.round(2) %>$</p>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-farmerando">
  <%= link_to "farmerando", dashboards_path, class: "navbar-brand" %>
  <%= link_to farmer_transactions_path do %>
    <i class="fas fa-comments-dollar navbar-icon"></i>
  <% end %>
  <%= link_to '#' do %>
    <i class="fas fa-store navbar-icon"></i>
  <% end %>

  <%= link_to my_products_path do %>
    <i class="fas fa-carrot navbar-icon"></i>
  <% end %>

  <%= image_tag current_user.img_url, id: "settings-cog", onclick: "toggleOn()", alt: "User Avatar", class: "avatar-navbar" %>

  <!-- <i class="fas fa-cog navbar-icon" id="settings-cog" onclick="toggleOn()"></i> -->
  <div class="settings-collapsed settings-hidden" id="cog-collapsed">
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

<script>
  const toggleOn = () => {
    const cog = document.getElementById("cog-collapsed");
    if (cog.classList.contains("settings-hidden")) {
      cog.classList.remove("settings-hidden")
    } else {
      cog.classList.add("settings-hidden")
    }
  }
</script>