config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
    resources :farmer_products, only: [:new, :show, :create, :edit, :destroy]
    get "profile", to: "users#profile"

    resources :buyer_preferences, only: [:new, :create, :edit, :update]
    get "profile", to: "users#profile"

    get "dashboards", to: "dashboards#show"

    resources :farmer_transactions, only: [:new, :create, :index, :show] do
      resources :transaction_products, only: [:create]
    end

    get '/confirm/:id', to: 'farmer_transactions#confirm', as: :farmer_transaction_confirmation

    get 'request_for_buyer/:id', to: "farmer_transactions#request_for_buyer", as: :request_for_buyer
    post 'reject_transaction/:id', to: "farmer_transactions#reject_transaction", as: :reject_transaction
    post 'accept_transaction/:id', to: "farmer_transactions#accept_transaction", as: :accept_transaction
    get '/my_products', to: "farmer_products#my_products"
end

app/controllers/farmer_transactions_controller.rb
# require 'date'

class FarmerTransactionsController < ApplicationController

  def index
    @farmer_transactions = FarmerTransaction.where(buyer_id: current_user)
  end

  def show
    @farmer_transaction = FarmerTransaction.find(params[:id])
    @buyer = FarmerTransaction.find(params[:id]).buyer
    @farmer = FarmerTransaction.find(params[:id]).farmer
    @transaction_product = TransactionProduct.new
  end

  def new
    @farmer_transaction = FarmerTransaction.new
    @farmer_transaction.buyer = User.find(params[:user])
    @farmer_transaction.farmer = current_user
    if @farmer_transaction.save
      redirect_to farmer_transaction_path(@farmer_transaction)
    end
  end

  def confirm
    @farmer_transaction = FarmerTransaction.find(params[:id])
    @farmer_transaction.status = "Confirmed"

    @total = 0

    @farmer_transaction.transaction_products.each do |tp|
      @total += tp.quantity * tp.buyer_preference.price
    end

    @farmer_transaction.total = @total

    @farmer_transaction.save

    redirect_to farmer_transaction_path(@farmer_transaction)
  end

  def request_for_buyer
    @farmer_transaction = FarmerTransaction.find(params[:id])
    @farmer = @farmer_transaction.farmer
    @buyer = @farmer_transaction.buyer
    @total = @farmer_transaction.total
  end

  def accept_transaction
   @farmer_transaction = FarmerTransaction.find(params[:id])
   @farmer_transaction.status = "Accepted"
   @farmer_transaction.save
   redirect_to farmer_transactions_path, notice: "Accepted!"
  end

  def reject_transaction
    @farmer_transaction = FarmerTransaction.find(params[:id])
    @farmer_transaction.status = "Declined"
    @farmer_transaction.save
    redirect_to farmer_transactions_path, notice: "Declined!"
  end


  private


  def farmer_transaction_params
    params.require(:farmer_transaction).permit(:buyer_id, :farmer_id)
  end
end



# Confirm the trasaction would be like the accept and reject of airbnb
# 1/ Custom route
# get '/confirm/:id', to: 'farmer_transactions#confirm'
# 2/ method in FarmerTransactions controller
# def confirm
# @farmer_transaction = FarmerTransaction.find(params[:id])
# # change status of transaction and redirect to the show of farmtransaction
# 3/ link in view (edited)

app/views/farmer_transactions/index.html.erb
<div class="container text-center mt-3 justify-content-center">
  <p>
    <%= current_user.first_name %>, here is a list of your recent offers
  </p>

  <% @farmer_transactions.each do |ft| %>
    <% unless ft.status == "pending" %>
      <div class="card card-bp p-4 shadow mb-3">
        <p>From <%= ft.farmer.first_name %> <%= ft.farmer.last_name %></p>
        <% ft.transaction_products.each do |tp| %>
          <div class="d-flex align-items-center">
            <div class='mr-2'><%= image_tag tp.buyer_preference.product.img_url, width: "30" %> </div>
            <p class="mb-0 mr-2 greeting"><%= tp.buyer_preference.product.name.capitalize %> </p>
            <p class="mb-0"><%= tp.quantity %>kg</p>
          </div>
        <% end %>
        <p class="mb-0 mt-3 text-left ">Total: <%= ft.total %></p>
        <p class="mb-0 text-left ">Status:
          <% if  ft.status == "Accepted" %>
            <i class="fas fa-check-circle mt-1 accepted"></i>
          <% elsif ft.status == "Declined" %>
            <i class="far fa-times-circle mt-1 declined"></i>
          <% elsif ft.status == "Confirmed" %>
            <i class="fas fa-hourglass mt-1 pending"></i>
          <% end %>
        </p>
        <div class="d-flex justify-content-between mt-2">
          <% if  ft.status == "Confirmed" %>
            <%= link_to "Accept transaction", accept_transaction_path(ft),remote: true, method: :post, class:'btn btn-main-small btn-green' %>
            <%= link_to "Reject transaction", reject_transaction_path(ft),remote: true, method: :post, class:'btn btn-main-small btn-red' %>
          <% end %>
        </div>
        <%#= link_to "Review", request_for_buyer_path(ft), class: "btn btn-transaction-small mt-3"%>
      </div>
    <% end %>
  <% end %>
</div>

app/views/farmer_transactions/request_for_buyer.html.erb
<div class="container">
  <p><%= @farmer.first_name %></p>
  <p><%= @farmer.last_name %></p>
  <% @farmer_transaction.transaction_products.each do |tp| %>
      <% if tp.quantity > 0 %>
        <div class="d-flex card-transaction justify-content-between align-items-center">
        <%= render "shared/card-produce-farmer-transaction", product: tp.buyer_preference.product, price: tp.buyer_preference.price%>
        <%= tp.quantity %> kg
        </div>
      <% end %>
    <% end %>
    <p>TOTAL: <%= @farmer_transaction.total %></p>
    <p>STATUS: <%= @farmer_transaction.status %></p>
  <div class="d-flex justify-content-between mt-2">
    <%= link_to "accept", accept_transaction_path(@farmer_transaction), method: :post %>
    <%= link_to "reject", reject_transaction_path(@farmer_transaction), method: :post %>
  </div>
</div>

app/views/farmer_transactions/show.html.erb
<div class="container text-center mt-3 justify-content-center">

  <% if @farmer_transaction.status == "Confirmed" %>

    <div class="card-confirmation">
      <div class="container row ">
        <div class="row h-100 p-2">
          <p class="col-10 text-left my-auto">
            <% unless @farmer_transaction.total.nil? %>
              <%= @farmer.first_name %>, you are trading with <%= @buyer.first_name %> <%= @buyer.last_name %>
            <% end %>

          </p>
          <div class="col-2 my-auto">
            <%= image_tag @buyer.img_url, alt: "User Avatar", class: "avatar" %>
          </div>
      </div>
      </div>
    </div>

    <div>
      <% @buyer.buyer_preferences.each do |bp| %>
        <div>
        <% if bp.transaction_products.where(farmer_transaction_id: @farmer_transaction.id).any? && bp.transaction_products.first.quantity > 0 %>
          <div class="d-flex card-transaction justify-content-between align-items-center">
                <%= render "shared/card-produce-farmer-transaction", product: bp.product, price: bp.price %>
          <%= bp.transaction_products.first.quantity %> kg
          </div>
        <% end %>
        </div>
      <% end %>
    </div>

    <div class="d-flex card-transaction justify-content-between align-items-center mt-4 p-3">
      <strong><p class="mb-0">TOTAL:</p></strong>

      <strong><p class="mb-0"><%= @farmer_transaction.total.round(2) %>$
      </p></strong>
    </div>

  <% else %>

    <div class="container row">
      <div class="col-10">
        <p>
        <%= @farmer.first_name %>, choose the amount to sell to <%= @buyer.first_name %> <%= @buyer.last_name %>
        </p>
      </div>
      <div class="col-2">
        <%= image_tag @buyer.img_url, alt: "User Avatar", class: "avatar" %>
      </div>
    </div>

    <div>

    <% @buyer.buyer_preferences.each do |bp| %>
      <% if @farmer.all_farmer_products.include?(bp.product) %>

        <div>

        <% if bp.transaction_products.where(farmer_transaction_id: @farmer_transaction.id).any? %>

          <div class="d-flex card-transaction justify-content-between align-items-center">
                <%= render "shared/card-produce-farmer-transaction", product: bp.product, price: bp.price %>
          <%= bp.transaction_products.first.quantity %> kg added
          </div>
          <% else %>
            <%= simple_form_for([@farmer_transaction, TransactionProduct.new], method: :post, remote: true) do |f| %>
              <div class="d-flex card-transaction justify-content-between align-items-center">
                <%= render "shared/card-produce-farmer-transaction", product: bp.product, price: bp.price %>

                  <%= f.input :quantity, input_html: { class: "rounded-input small-input mb-0"}, placeholder: "kg",
                      label_html: {class: "d-none"} %>

                  <%= f.input :buyer_preference_id, as: :hidden, input_html: { value: bp.id } %>
                  <%= f.button :submit, 'Sell', class: "btn-transaction-small" %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% unless @farmer_transaction.total.nil? %>
    <div class="d-flex card-transaction justify-content-center align-items-center">
      <span> You will receive <%= @farmer_transaction.total.round(2) %> $ from <%= @buyer.first_name %> <%= @buyer.last_name %> </span>
    </div>
  <% end %>
    <div class="button-send mb-2">
    <%= link_to "Send!", farmer_transaction_confirmation_path(@farmer_transaction), class: "btn btn-main"%>
    </div>
 <% end %>
</div>